name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assemble:
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      name: Assemble
      tasks: assembleDebug

  unit-test:
    uses: ./.github/workflows/shared-workflow.yaml
    with:
      name: unit-test
      tasks: testDebugUnitTest


  dependency-submission:
    runs-on: ubuntu-latest
    needs: [ 'assemble', 'unit-test' ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          dependency-graph: download-and-submit
